# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

  - name: Conda Environment Setup
    init: |
      wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      bash Mambaforge.sh -b -p "${HOME}/conda" && rm -f Mambaforge.sh
      source "${HOME}/conda/etc/profile.d/conda.sh"
      source "${HOME}/conda/etc/profile.d/mamba.sh"
      mamba create --name mlopsproject --file week3/project/requirements.txt

    command: |
      mamba activate mlopsproject
      echo "<peon voice> Ready to work!"

  - name: Start Server
    init: cd week3/project/app/

    command: uvicorn server:app --reload

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
