# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

  - name: Conda Environment Setup
    init: |
      wget "https://repo.anaconda.com/miniconda/Miniconda3-py39_23.3.1-0-Linux-x86_64.sh"
      bash Miniconda3-py39_23.3.1-0-Linux-x86_64.sh && rm -rf Miniconda3-py39_23.3.1-0-Linux-x86_64.sh
      conda create --name mlopsproject --file week3/project/requirements.txt

    command: |
      conda activate mlopsproject
      echo "<peon voice> Ready to work!"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
